### ISSUE TITLE
Change repeated keys to arrays

### ISSUE THREAD

**Issue by superroma** [beerjson/beerjson#1]
Currently JSON schema converted from XSD contains multiple repeated keys, for instance `Fermentables` can contain multiple instances of `Fermentable`. This might be ok for JSON, but cannot be easily deserialized into JS object or hashtable, so let's change such collections to arrays.

**Comment by krutilin** [comment]
Started working on fixes in the following brunch
https://github.com/beerjson/beerjson/tree/Use-arrays-for-nested-objects-with-same-key

**Comment by krutilin** [comment]
And need to implement same stuff for the beerjson 1.0

**Comment by krutilin** [comment]
done
