### ISSUE TITLE
Add BeerXML 1.0 -> BeerJSON converter

### ISSUE THREAD

**Issue by superroma** [beerjson/beerjson#10]
danlatimer2 suggested to add a converter from BeerXML 1 to any new BeerJSON standard
https://www.reddit.com/r/Homebrewing/comments/7ej733/bregrammers_lets_work_on_beerjson_beerxml_2/dq5deak/

**Comment by krutilin** [comment]
I think it is possible with some approximations and defaults of course. In beerxml 1.0 there are set of the fields that have conditional measures for the units.

**Comment by krutilin** [comment]
@beerjson/beerjson-wg implemented basic converter. need pull review.
