### ISSUE TITLE
XML to JSON conversion, and samples.test

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#102]
Is it possible to update the samples.test file to 

1) Test all files in the generic and real tests folders, will make things easier for maintenance IMO.  

2) Create a new folder in tests for the saved conversions from the testXMLtoJSON conversions, which should be for any XML file in the tests/data folder (rename to tests/xml?) Which should then be tested against the json schema to make sure the conversion is outputting good data?

This way we could for example do mass conversions to beerJSON of a larger database of beerXML recipes, which would be useful, and also will be helpful in making sure all variables are caught in the XMLtoJSON conversion.

**Comment by krutilin** [comment]
1) It is possible. 
2) Possible too. 
But need some time to implement.

**Comment by pricelessbrewing** [comment]
Converted files don't appear to go through prettier formatting.

**Comment by pricelessbrewing** [comment]
There are quite a few issues I see with the converted files, which has to do with 1) the conversion, and 2) Them passing the test due to not enforcing enough "additionalProperties": false. I think these need to be added not to just for example FermentableBase, but also FermentableType, and FermentableAdditionType. 

Similarly for all the schema. It might be necessary for measurable units as well, since color is accepting "l" as an allowed unit, when "L" is a volume unit and not a color unit, which is "lovi". 

For example, 

Fermentables colors are allowing "l" as an acceptable unit, when it should be mapped to "lovi". 

All ingredients addition timings should be mapped through to the new timing object. Any references to "add after boil" "add to mash" etc should be treated accordingly and mapped to the appropriate timing object process steps. 

Fermentables yield needs to be remapped to the new yield object.
