### ISSUE TITLE
Fix Fermentation Stages

### ISSUE THREAD

**Issue by rcaller** [beerjson/beerjson#12]
A long standing beerXML issue is that it has no way to represent stepped or ramped fermentation profiles.

I suggest moving to an array of fermentation steps, each with a start and end temperature and a duration.  This is how I represent fermentation profiles in my fermentation control software.

We might need to add a transfer counter to represent primary, secondary etc.

This leaves an issue about how to represent free rise, which I don't have an answer for.

**Comment by m00nh34d** [comment]
Probably do away with the fixed fermentation stages in the definition as well ("primary", "secondary", "tertiary", "conditioning"). With the complex fermentation profiles out there now, especially when dealing with brett/sour beers, having these fixed steps doesn't really work.

A fermentation stage could probably be it's own object, with many properties and attributes.

As suggested here, start and end temperatures, time, and something to account for free rise (maybe just a bool?). I'd suggest other attributes like if it's a diacetyl rest (which feeds back to time, making it "until it's ready"), strain of yeast used (sacc, brett, lacto, pedio, etc), fermentation vessel (fermenter, carboy, bright tank, barrel, bottle).

**Comment by nicknotto** [comment]
This should also have the option to be based on gravity instead of duration since some systems use that via Tilt, iSpindel, etc.

**Comment by superroma** [comment]
I'm not a pro brewer, but I suspect that stages are specific to the fermentation vessel, if I do everything in a conical and then bottling - do I have a single stage?

**Comment by superroma** [comment]
> I've written the base of this suggestion (created fermentation_step.json definition and updated recipes.json), not really sure how to publish/share it though.

@m00nh34d please [create a pull request](https://github.com/beerjson/beerjson/compare)

**Comment by m00nh34d** [comment]
Okay, think I figured out how to do this who github thing. Created a fork with my changes and a pull request from that... Looks like the tests are failing as I'm pointing the "id" attribute to this github URL, not my fork where my new file exists.

> I'm not a pro brewer, but I suspect that stages are specific to the fermentation vessel, if I do everything in a conical and then bottling - do I have a single stage?

That's up to the recipe writer I suppose. I'd just list that as a single fermentation step, well, maybe 2 as I'd also throw in a d-rest at the end. But some brewers, especially Belgians, would consider the secondary fermentation that happens when bottle conditioning to be an important part of the fermentation process, in which case it should be possible to represent that in the recipe. (But probably more important for things like brett/sour fermentations which require complex schedules and multiple strains of yeast/bacteria - http://www.milkthefunk.com/wiki/File:Long_Fermentation.jpg)

**Comment by krutilin** [comment]
Guys, I made attempt to store one of fermentation profiles from BeerSmith in the JSON form according to our schema https://github.com/beerjson/beerjson/commit/d71faf7c6ee4cdd7e37e93e0b24183c976702e6f And does not like the result.

Also found that fermentation profile is very close to mash profile. In each case, we have some root element with basic descriptions and array of steps. 
So I suggest adding some field to the root fermentation procedure and array of steps. And then put it in the root of beerjson as independent fermentation item too.

something like

```
      {
        "name": "Ale, Single Stage",
        "notes":"A simple single stage fermentation, often used by extract brewers or for classic ales.",
        "type":"Single Stage"
         ... other fields ...
        "fermentation_steps": [...]
      }
```
What do you think about it?

**Comment by m00nh34d** [comment]
The fermentation steps are pretty much a copy of the mash steps right now, just with different fields. Interesting that the mash steps don't need a root element, is that because it's in a separate object again? Bit of a pain it doesn't like it without a root element. BUT, maybe going back to the other good point about having the order of the steps included, maybe we can have a description and the number of steps at the root, then add an "order by" field for each step to help out. I do note there's no order on the mash steps either, while any implementation *might* be able to figure this out, it's a bit of an assumption.

**Comment by superroma** [comment]
Well, array is an ordered structure, why do you need to sort it?
[{step1...}, {step2...}] clearly indicates that step1 is the first and step2 is second.

**Comment by krutilin** [comment]
I extracted fermentation to the independent object, like mash procedure. Please review it https://github.com/beerjson/beerjson/commit/7e7e371bd5098e83f8947960ea6c2bf1e8db1b0d
I am not sure about correct fieldset and required fields. But general structure of fermentation object looks good.

(Note. I am not a professional brewer and did less than 10 brewing sessions.)

**Comment by superroma** [comment]
I guess you need to do a mention: 
@m00nh34d, can you please look at this commit https://github.com/beerjson/beerjson/commit/7e7e371bd5098e83f8947960ea6c2bf1e8db1b0d

**Comment by m00nh34d** [comment]
Sorry, I did see the comments, just life got in the way...

Re: array ordering, we're defining the data structure here, the implementation of that structure is what will determine if the data is ordered, some programming languages, for example, do not honour the order of arrays, you need some other value to use to keep them in order. Same goes for output, If you've got a step called "Pedio Ferment", then another called "Brett Ferment", which one would you put first? You can assume, but it doesn't help define the recipe.

Re [7e7e371](https://github.com/beerjson/beerjson/commit/7e7e371bd5098e83f8947960ea6c2bf1e8db1b0d), it looks like this is just back to the original beersmith/beerXML format of having "Primary", "Secondary", "Tertiary" steps, there's no way to handle the complex fermentation profiles we use nowadays, and there are no measures for tracking things like gravity or pH which is often a more frequent driver of fermentation step changes, than time. (also, nothing about D-rest, free rises, yeast type, vessel, etc...)

**Comment by superroma** [comment]
Well, JSON [standard says](http://www.rfc-editor.org/rfc/rfc7159.txt) "An array is an ordered sequence of zero or more values." - in contrast to object, whos members are unordered, but named.
And the essense of array in languages i know is the same - you address items by index - steps[2] can refer to 2nd or 3rd item depending on implementation, but there is no other way to address particular item in array, if order is not preserved, arrays became sets which is different structure...

**Comment by jdominiczak** [comment]
I do like direction of the 7e7e371 commit.  It makes sense to 0 to n stages that are not tied to the 15 year old mantra of Primary/Secondary/Tertiary.  Furthermore, as we build systems that utilize this for controlling fermentation (such as BrewPi), the flexibility to use new devices (such as the Tilt and the DIY version) to get away from a strictly time based step measure.  

The additional optional properties that @m00nh34d added are great, I just worry about the microorganism type and name fields....  The Yeast record already has a field  "add_to_secondary" which I hate.  Would it not make more sense to reference the bugs (or yeast) that will be added in a fermentation stage in the Yeast record?  If so, how best would we do it to avoid referential hell?

**Comment by m00nh34d** [comment]
Yeah, not sure about the yeast being in the fermentation step. I mean I kind of see it as important for multi-stage fermentation, but it does make more sense to have it listed as an ingredient and then it reference the step it's used in. But, jeez, that's a confusing setup. Is it possible to link the 2 objects together like that in this definition? Like either the ingredient or fermentation step is linked to an already existing fermentation step or ingredient?

**Comment by jdominiczak** [comment]
I've done a pull request that I think handles yeast/bacteria additions to a fermentation stage here d78aca

**Comment by m00nh34d** [comment]
What does the fermentation_step integer link to? There's no id's on the fermentation step.

**Comment by jdominiczak** [comment]
It was just a number that would reference the fermentation stage (ie 1, 2, 3...n).   Another way would be to reference the required fermentation stage name attribute.  That may actually be a cleaner approach.

**Comment by krutilin** [comment]
@jdominiczak @m00nh34d https://github.com/beerjson/beerjson/commit/d78aca6d2c40f2d38e84c60a1b2be156805d080c looks reasonable. I want to accept it if there are no any objections.

And then I'll add some additional tests for yeasts and fermentation data structures.
