### ISSUE TITLE
FermentationProcedureType: Type:{String} necessary?

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#130]
I'm referring to 

https://github.com/beerjson/beerjson/blob/f5859cf98f615c591d53b284e485d7fd606de6e9/json/fermentation.json#L15

The only test case for it being used is in the medieval ale, and the use case is redundant when looking at the name of the fermentation, as well as the number of steps. Moreover, it accepts any string. 

What was the intended use for this property, and can it be removed without any loss of function?

https://github.com/beerjson/beerjson/blob/master/tests/real/MedievalAle.json

**Comment by krutilin** [comment]
Yes looks like redundant.
