### ISSUE TITLE
Fermentables - Include maltster spec sheet properties

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#132]
Would be helpful for sharing ingredient databases with maltsters and pro brewers, many of which care about some of the more detail oriented specs listed below. 

Additionally, if every maltster spec property is supported, then we may be able to get maltsters to support by releasing ingredient files themselves rather than relaying on a 3rd party to translate the typical spec sheet PDF to a file.

**Comment by pricelessbrewing** [comment]
Lot #

Glassy % Used to indicate the "crystallized" percentage of starches for crystal malts.

Plump % The percentage of grain that masses through sieves with gaps of 7/64 and 6/64, desired values of 80% or higher which indicate plump kernels.

Half %

Mealy % The opposite of glassy, a mealy kernel is one that is not glassy. Base malt should be at least 90%, single step mashes generally require 95% or higher.

Thru % : The Percentage of grain that makes it through a thin mesh screen, typically 5/64". Values less than 3% are desired. 

Protein % The percentage of protein. Higher values may indicate haze or lautering issues.

Kolbach Index The ratio of soluble protein to total protein, a value of less than 30% may suggest difficult lautering.

Friability Friability is the measure of a malts ability to crumble during the crush, and is used as an indicator for easy gelatinization of the grain and starches, as well as modification of the malt. Value of 85% of higher indicates a well modified malt and is suitable for single step mashes. Lower values may require a step mash.

DiPH - The pH of the resultant wort for 1 lb of grain mashed in 1 gallon of distilled water. Used in many water chemistry / mash pH prediction software.

Viscosity (cP - Centipoise units) The measure of wort viscosity, typically associated with the breakdown of beta-glucans. The higher the viscosity, the greater the need for a glucan rest and the less suitable for a fly sparge. 

DMS-P (PPM) The amount of DMS precursors, namely  S-methyl methionine (SMM) and dimethyl sulfoxide (DMSO) in the malt which convert to dimethyl sulfide (DMS). 

FAN Free Amino Nitrogen (FAN) is a critical yeast nutrient. Typical values for base malt is 170. 
Fermentability -  Used in Extracts to indicate a baseline typical attenuation for a typical medium attenuation yeast. 

Beta Glucan PPM. Values of 180 or more may suggest a glucan rest and avoiding fly sparging.

**Comment by PierreSmits** [comment]
Yes, I would like to see that happening. 

If helpful I can make such available via the CPM (Catalog/Product Management) component of  my brewery-demo site (based on BMS4Breweries).

Best regards,

Pierre

**Comment by pricelessbrewing** [comment]
Feel free to add any properties missing from my list above to this issue so we can add a single PR once we have a full list.

I'm in the middle of a kitchen remodel so won't be able to commit any code for a week or two.

**Comment by PierreSmits** [comment]
If we want to have this, then I suggest that a list of matters is compiled with from each an example of the specs they provide so that an overview of similarities can be established. Which can then be used to work on integration. 

Otherwise we might be getting chaos (inconsistencies) introduced.

**Comment by pricelessbrewing** [comment]
I went through the publically available maltster spec sheets from most of the big companies and think adding the above will cover almost all specs. Once it's added, I can reach out to some of my contacts and see if there's anything they think would need to be added to support their product catalog.

**Comment by PierreSmits** [comment]
Which malters were you talking about. I can image that there may be quite a list across the globe.

**Comment by pricelessbrewing** [comment]
@PierreSmits  I checked with the largest ones first, rahr, malteuro, weyermann, and briess. 

I think the above should be sufficient as it covers all of the typical and many of the common but atypical properties as well. What we can do is similar to the reach out to software devs, once we get to draft 1.0 we can reach out to maltsers and get some feedback.

**Comment by RossMerr** [comment]
@pricelessbrewing  I'm guessing no one did a PR for that then? I'm happy to have a go on it next week to get the issue moving.

**Comment by pricelessbrewing** [comment]
@RossMerr nope, I was planning on doing it but ended up having to move across states, a kitchen remodel and then working two jobs so been busy. It's pretty straightforward since it's just adding properties. 

Let me know if you have any questions
