### ISSUE TITLE
Conformation to unit standards (ISO/others)

### ISSUE THREAD

**Issue by PierreSmits** [beerjson/beerjson#138]
While looking through the various examples in /tests/real I noticed that these recipes contain units of measures that are not conforming to standards, like:
- gal

We should conform to the naming of the standardization bodies (see 1), to avoid ambiguity and misunderstanding. This will make it easier to ensure that recipes (in the various software solutions) in local languages.

(1)
- https://en.wikipedia.org/wiki/System_of_measurement
- https://en.wikipedia.org/wiki/International_System_of_Units
- https://en.wikipedia.org/wiki/Unified_Code_for_Units_of_Measure

What are your thoughts?

**Comment by superroma** [comment]
Hi, beerXML has chosen an approach to keep recipe as it is - with whatever units is there.
If it is 2 tablespoons - let it be 2 tablespoons. And beerJSON obviously is using the same approach.

This is a just a data transfer format, so if you want to export in CI units - it is clearly possible.

**Comment by pricelessbrewing** [comment]
We can add some info on the readme and documentation specifying that units follow SI and US customary units wherever applicable if it's deemed necessary. 

Of relevance to the example above, gal is the official us customary unit for gallon.

**Comment by f3ndot** [comment]
It's a challenge. I can't seem to decide.

* Sticking to SI feels like the most appropriate thing to do when defining a global standard
* Lots of recipes I've encountered deals with non-SI units, like gallons and quarts. At least in North America
* Supporting multiple units, both SI and non-SI in the spec/format itself feels like an anti-pattern.

If the goal is that the JSON is directly human readable, then supporting non-SI units seems desirable. If the goal is a simple, concise schema, then selecting only one set of units (SI) makes the most sense.

Ultimately, at the end of the day, I feel like supporting only the single set of SI units is best:

* This JSON structure, while human-readable, is meant first and foremost for machines.
* It would be unwise to assume the whole world uses Imperial units. SI is the most accessible, even if awkward to the human eye
* We keep the standard and concise. I don't want to end up with the OAuth 2.0 RFC spec equivalent of beer recipes.
* The importing software can perform conversions as needed, why have the data interchange format do the work?
