### ISSUE TITLE
Add BeerXML/JSON  1.0 -> 2.xx converter suggestion

### ISSUE THREAD

**Issue by krutilin** [beerjson/beerjson#14]
https://www.reddit.com/r/Homebrewing/comments/7ej733/bregrammers_lets_work_on_beerjson_beerxml_2/dq6f48y/

There were attempts to implement this kind of conversion for beerxml. So this opotunity could be implemented as beerjson tooling part.

**Comment by gigatropolis** [comment]
These types of conversions are in progress in this project: 
[https://github.com/gigatropolis/beercnv](https://github.com/gigatropolis/beercnv)

  Working on BeerXML 1.0 to BeerXML 2.0 and will be finished by end of the month. The project will include a web server with APIs to do the conversions. I'll post Binaries for different platforms that can run  the web server (This is easy to do in Go language and one of its strengths). 

 Thee projects should play nicely with each other. Will keep beerjson project as the standard for how xml/json should be implemented

Web server and First XML->XML2 conversions should be posted by end of February, 2018

**Comment by krutilin** [comment]
Will close. it is duplicate for #10
