### ISSUE TITLE
Can we have standard of brew logs?

### ISSUE THREAD

**Issue by vitotai** [beerjson/beerjson#141]
For wort making, volume and gravity records in each step are obvious. Maybe pH measurement can also be added.

For fermentation log, gravity is the most important information. Now that we have TILT and iSpindel, sharing gravity trends would be great. Later or sooner, there will be AI programs to tell how the fermentation goes.

**Comment by pricelessbrewing** [comment]
@vitotai Just to keep the issue page clear, this is related to #56 so I'm going to close this. At the moment we don't have anything planned for measured values. It may be as simple as the measured values being stored in a separate recipe file with different values for any given property, then a separate schema is not needed.
