### ISSUE TITLE
Remove redundant properties in mash.json and mash_step

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#147]
Redundant information, as sparge temperature should be treated via a mash step using sparge as the mash step type and infuse temperature instead of sparge temperature. 

Remove

https://github.com/beerjson/beerjson/blob/ffad2fc9ca07bfb5e3c5d3393476370c4ca2b6dd/json/mash.json#L18

Similarly, mash pH should be removed from mash.json, as you will have different pH's at each mash step depending on water grain ratios, and if ingredients are added after the initial mash strike step. 

Remove 

https://github.com/beerjson/beerjson/blob/ffad2fc9ca07bfb5e3c5d3393476370c4ca2b6dd/json/mash.json#L21

**Comment by tbrnslv** [comment]
Hello,

please check https://github.com/tbrnslv/beerjson/tree/sparge-to-mash-step

During xml to json conversion I moved sparge_temp and sparge_ph as additional sparge step inside mash_steps. The problem is sparge_ph field, as there are 2 ph fields in mash_step (start, end), but I guess sparge_pg should represent ph of added water for sparging... Also, time is required field in mash step.

Maybe we should add ingredients inside mash_steps? So then we could put water as ingredient of mash_step with sparge_ph as ph value. That would probably be good if someone whant to add more ingredients during separated mash steps.

Please let me know your opinions. This projects looks great, I would also like to help this repository in future, both with proposals and code.

**Comment by pricelessbrewing** [comment]
Hello tbrnslv, welcome! 

Good points regarding the conversion from beerXML 1.0, to beerJSON. 

What I would suggest is that we convert beerXML to mash step 1's start pH, as it's most common for Brewers to wait ~5-10 minutes for the pH to stabilize and record that value as the mash pH.  The only time end pH will be significantly different from start pH is when you're performing a souring step, otherwise there will only be minor fluctuations.


Ingredients are currently supported to be added to any process step using the addition timing object which describes an ingredient addition with basis of time, sg, or pH. So you can add a dry hop at any fermentation step at any gravity, a common practice for neipa recipes. 

Water is the only ingredient that is not treated as such. Perhaps we should circle back to that idea and consider what consequences of not treating it as an ingredient.

**Comment by tbrnslv** [comment]
Ok, I will then leave sparge_ph as start_ph. And what do you suggest to put as default step time in conversion?

**Comment by pricelessbrewing** [comment]
I don't think there's any need for either sparge_pH or start_pH in the mash.json schema.

Any references to pH should be made in the mash_steps schema, as it will be different for every mash step where any ingredients, or water volume is changed. A mash pH at 1.25 qt/lb (2.6L/kg) is going to be different then the following step if I add water to bring the thickness to 2 qt/lb (4.173 L/kg). 

Instead the beerXML mashpH should be mapped to mash_steps[0].start_pH

**Comment by tbrnslv** [comment]
Ok, but PH in MASH inside BeerXML represents sparge water addition ph as I understand. So both start_ph and end_ph can be totally different from it. That was the main reason I suggested to have some way to put water as an ingredient during mash steps.
Also, we need some approximation for mash_step time if mash_step type is 'sparge'.
Maybe also to add type of sparge somewhere in mash step ('fly' or 'batch') and we would need approximation when converting from BeerXML for that also...

**Comment by tbrnslv** [comment]
I will try to make something up today or tomorrow in my fork repo, so I will let you know to look it up when I finish.

**Comment by pricelessbrewing** [comment]
Thanks, you're absolutely right the xml property for pH in mash xml was for sparge pH. 

It's unclear in the xml documentation if that was supposed to refer to the sparge waters initial pH, the starting pH of a fly sparge runoff wort, or the final pH of the runoff wort. I would think that it's the final pH of the wort runoff. 

However again this is unclear which step it would refer to, and I would prefer to use the approach via mash step properties. We will have to look at some software to see how that property is actually being used. 

There is already a mash step for "sparge", but I'm not opposed to being more explicit and changing it to batch sparge and fly sparge.

**Comment by tbrnslv** [comment]
Ok, you can check my fork now. To summarize what I added.

1. if SPARGE_TEMP exists in MASH, create mash_step as last of the mash steps with type 'sparge', temperature as in SPARGE_TEMP and default step_time of 15 minutes
2. if PH exists in MASH, create water_addition with timing 'add_to_mash' and put step as the last mash step which is sparge
3. I added timing property to water additions and ph as ph exists in both BeerXML 1.0 and proposed BeerXML 2.01 on waters

If all is ok with you I can maybe refactor a little and do pull request later.

Maybe it would be best to make more complex xmlToJson converter that would accept some parameters how to handle this kind of situations. Also jsonToXml would probably be a good idea, just to be backward compatible, as BeerXML is still leading format for homebrewers.

Also, maybe we could separate sparge completely from mash. So we can have sparge steps? Maybe that will be more useful if somebody want to do some kind of hybrid multi sparges with 2 different water additions, batch, then sparge combination or something like that.

**Comment by pricelessbrewing** [comment]
Alright, I checked with the biggest brewing softwares, beersmith, brewersfriend, brewtarget, and brewfather. None use the pH property as described in the XML standard. 

Beersmith has MH_PH, and runoff_PH keys.
 brewersfriend has a mash pH property onthe website, but it is not exported (probably due to unclear documentation but I can confirm with the owner).
 Brewtarget has no option to record pH anywhere. 
Brewfather has calculated values for mash pH, sparge water pH, but I do not see anything for runoff pH. Was not able to confirm with an exported recipe as it requires a premium account. 

If the mash pH key from the XML schema is not actually being used by anyone, then I would say lets ignore it and just remove it for the reasons I've stated previously. Every step will have a different mash pH (stored in mash step object), water infusion pH (which should be stored in the water ingredient object), and a different runoff wort pH (stored in mash step object with type "drain mashtun"). 

@krutilin the mash pH property is used in a couple of the test XML files, but I don't know where those came from. Where they created from the XML schema directly, or exported from software? 

@tbrnslv re: 3. This should be a separate issue and PR. Please open an issue for treating water as an ingredient with the corresponding addition properties (timing object specifically).

**Comment by tbrnslv** [comment]
ok, I removed all things that had to do with ph from my code and made a merge request.

**Comment by krutilin** [comment]
Test XML recipes are recipes exported from the BeerSmith2, as I remember. And yes we should have good xmlToJson and jsonToXml converting tools.

**Comment by pricelessbrewing** [comment]
Thanks tbrnslv, and krutlin. I'm going to close this and reopen two new issues:
Splitting sparge mash step into batch sparge and fly sparge
Adding the addition object, and timing addition object to water.json
