### ISSUE TITLE
Should Hop year field be an integer rather than a string?

### ISSUE THREAD

**Issue by matty0ung** [beerjson/beerjson#196]
In https://github.com/beerjson/beerjson/blob/master/json/hop.json, the `year` field is a string.  Wouldn't it be better as a range-constrained integer?

**Comment by LinusU** [comment]
Not sure about the range-constraint though, when archeologists excavates an intact jar of hops from the ruins of Pompeii we need to be able to accurately record the recipe of the beer they brew with it 😉

**Comment by matty0ung** [comment]
I would have thought a four-digit integer would cover almost all the foreseeable cases.  (Maybe there are records of hop harvests before the year 1000, but I'm guessing not.  And at the other end of the scale, I'm sure in 7978 years' time there will be at least v2 of BeerJSON to address the Y10K problem. :smile:)

I'm not going to die in a ditch over it, but my general instinct is that if there are some sane bounds for a field then we should apply them as it makes it easier to automatically detect other errors (such as if someone gets their fields mixed up).  After all, that is one of the benefits of having a machine-parseable schema (as opposed to the (in)famous Word document that defined BeerXML...).

**Comment by LinusU** [comment]
> I'm not going to die in a ditch over it, but my general instinct is that if there are some sane bounds for a field then we should apply them as it makes it easier to automatically detect other errors (such as if someone gets their fields mixed up).

Good point 👍 

> After all, that is one of the benefits of having a machine-parseable schema (as opposed to the (in)famous Word document that defined BeerXML...).

Haha, I did not know of that origin, but can totally see how it happened 😄

**Comment by matty0ung** [comment]
I've thought about this some more (as I work through the implementation in Brewtarget).  I guess the advantage of keeping year as string rather than an integer is that we don't have to have special formatting rules for it.  People write "2023" for the current year, not "2,023" or "2 023" etc.
