### ISSUE TITLE
Implement xsd:choice in the root schema

### ISSUE THREAD

**Issue by superroma** [beerjson/beerjson#2]
Root JSON schema defines an object with these required (!) properties:
* version
* fermentables
* miscellaneous_ingredients
* hop_varieties
* cultures
* profiles
* styles
* procedure
* recipes

While XSD schema defines `version` element, followed by `<xsd:choice>` of all others - meaning there should be required `version` property and **one and only one** of the other properties.

**Comment by krutilin** [comment]
same stuff for misc and yeast additions.

**Comment by krutilin** [comment]
fixed
