### ISSUE TITLE
PRs for documentation improvements

### ISSUE THREAD

**Issue by matty0ung** [beerjson/beerjson#206]
While working on BeerJSON support for [Brewtarget](https://github.com/Brewtarget/brewtarget), I've noticed that the BeerJSON [docs](https://beerjson.github.io/beerjson/) are sometimes missing field descriptions or explanations that are present in the [BeerXML 2.01 document](http://users.speakeasy.net/~antonw/beer_xml/BeerXML_v2_01.pdf).  Eg, [MashStepType](https://beerjson.github.io/beerjson/mash_step.json.html) doesn't offer descriptions for `step_temperature` or `end_temperature` but the PDF does, which helped me understand (I hope!) the difference between the two fields.

Would the project be interested in PRs to add in the "missing" descriptions?  Or is it intentional that some things did not come across from the PDF?

**Comment by superroma** [comment]
As I remember, initial data was taken from XML files, so probably PDF contained more descriptions.

In any case, adding or refining descriptions would be great, so suct PR are welcome!

**Comment by matty0ung** [comment]
Any chance of someone approving https://github.com/beerjson/beerjson/pull/199 and https://github.com/beerjson/beerjson/pull/200?

**Comment by krutilin** [comment]
I fixed tests after merge. Closing the issue.
