### ISSUE TITLE
"Efficiency" replaced with "Brewhouse Efficiency" and complete Efficiency Set

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#21]
All current references to "Efficiency" should be replaced by "Brewhouse Efficiency", and should be a required correction, with the conversion efficiency, lauter efficiency, and mash efficiency variables as optional. 

In addition to the name, required, format, and description I added columns for typical values, as well as placeholder columns for formulas if that's something we want to pursue which I think we should in order to ensure all software following this standard is using equivalent formulas. They can additionally provide optional alternative formulas, such as the different refractometer formulas, or the different ABV formulas as desired.  

https://docs.google.com/spreadsheets/d/1Aiv3H1rPhNtXykliTbqBf-c9WRvLF2_jnJK9Uqc3VdI/edit?usp=sharing

**Comment by krutilin** [comment]
Agree. Efficiency is more complex value than just percentage and we should reflect it in the structure. But I am not sure where better to store it in the schema. Is it part of the recipe or it is part of the concrete equipment?

**Comment by pricelessbrewing** [comment]
Since the current placement of "efficiency" is in recipe, I would say there's precedence of keeping it all in recipe. Alternatively, if you feel that clutters the recipe schema too much, then equipment would be the next best place.

**Comment by jdominiczak** [comment]
@pricelessbrewing I agree that efficiency should be replaced by a brewhouse efficiency metric.  This is the only way to truly map the fermentable input to the wort OG.  When brewing someone else's recipe, adjusting the efficiency to my system is the first step so that fermentables can be scaled appropriately to hit OG numbers.  I do like the option for conversion efficiency, lauter efficiency, and mash efficiency.

**Comment by pricelessbrewing** [comment]
So I propose keeping it in it's current location, in recipe.json, but changing efficiency to an element, with conversion, lauter, mash, and brewhouse as subset percentages. 

The problem I see with placing it in the equipment.json is that it's really used to describe the brewing process, and has a direct affect on the flavor profile of the beer (especially for specialty malts). If it's placed in equipment, we lose that connection. 

Data tag | Required | Format | Description
------------ | ------------- | ------------- | -------------
Efficiency | Conditional | Element | Contains all subelements necessary to fully describe the efficiency at each step in the brewing process.   Not required for “extract” recipes, but is required for “partial mash” and “all grain” recipes. 
Conversion| Conditional | Percentage| The percent Conversion Efficiency is a the percent of the total amount of extract available from your grains, the potential extract, to the amount of sugar converted from the mash. The measurements needed are total volume of water added during the mash, the grain bill, and gravity of the first runnings of the mash. This is fairly static across recipes, and is mainly determines by crush but secondarily by the mash pH, the dough in process, and any recirculation during the mash.  Not required for “extract” recipes, but is required for “partial mash” and “all grain” recipes. 
Lauter | Conditional | Percentage | The percent Lauter Efficiency is a the percent of the total amount of extract available in the mash, the converted extract, to the amount of extract present at preboil. The measurements needed are total volume of water added during the mash, the grain bill, gravity of the first runnings of the mash, the volume and specific gravity of preboil. This is variable across recipes, as the mash process and total amount of grains has a predictable influence on the lauter efficiency.  Not required for “extract” recipes, but is required for “partial mash” and “all grain” recipes. 
Mash | Conditional | Percentage | The percent Mash Efficiency is a the percent of the total amount of extract available from your grains, the potential,extract, to the amount of extract present at preboil. The measurements needed are total volume of water added during the mash, the grain bill, gravity of the first runnings of the mash, the volume and specific gravity of preboil. This is variable across recipes, as the mash process and total amount of grains has a predictable influence on the lauter efficiency.   Not required for “extract” recipes, but is required for “partial mash” and “all grain” recipes. 
Brewhouse | Conditional | Percentage | The percent Brewhouse Efficiency is a the percent of the total amount of extract available from your grains, the potential,extract, to the amount of extract present in the fermenter. The measurements needed are total volume of water added during the mash, the grain bill, gravity of the first runnings of the mash, the volume and specific gravity of the finished wort in the fermenter. This is variable across recipes, as the mash process and total amount of grains has a predictable influence on the lauter efficiency which in turn effects mash and brewhouse efficiencies.  Not required for “extract” recipes, but is required for “partial mash” and “all grain” recipes. 


I know the descriptions are lengthy, so feel free to make it more concise as needed.
