### ISSUE TITLE
Include mashtun and kettle loses 

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#22]
In order to create a more descriptive recipe, the mashtun losses, and kettle losses should at least be included as they have a direct influence on the flavor profile of the wort via dilution of hops, and grain. Inclusion of mash and brewhouse efficiency as distinct measurements is a great step but doesn't tell you the whole story.

Not sure if we want to create an additional set for all volumes, or just add it to the recipe set near batch size and boil volume.

**Comment by krutilin** [comment]
Yes, it is reasonable. Equipment losses affect brewing process. I think we should add these losses to the equipment profile. Because this is part of the equipment object, but not the recipe. #19
