### ISSUE TITLE
Replace "Yeast" file with "Microbe" or "Culture"? [Poll]

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#27]
I suggest replacing the generic file structure and category of "yeast" with either "microbe" or "culture". This would include sacc, brett, and wild yeasts, as well as any bacteria added to the recipe. 

Data tag | Required | Format | Description
------------ | ------------- | ------------- | -------------
microbe | yes | Element | May be “Ale”, “Brettanomyces”, "wild yeast", “Champagne”, “Cider” “Kviek”, “Lager”, “Mead”,  “Spontaneous”, “Wheat”, or “Wine”. 

Additionally amount, and form should be made “conditional” as Spontaneous would not include any amount, or form. Wild yeast would designate a spontaneously captured, and/or cultured yeast of unknown origin. Spontaneous would indicate no cultured yeast is added, and the wort is innoculated spontaneously via the air, or a coolship. 

Vote via thumbs up or thumbs down.

**Comment by pricelessbrewing** [comment]
On this topic, what's up with "wheat"? The only listed entries in brewtarget are from white labs, and they do not label their yeasts as "wheat" but either ale,  lager, then are provided styles that they're commonly used for.

I'd say we should lose that.

**Comment by pricelessbrewing** [comment]
I think I have this completed, but I need to figure out how to install node and run the npm test locally so I don't keep submitting bad pull requests that fail the test.

**Comment by rmsrosa** [comment]
I am not sure I am late for this, but wouldn't **"microorganism"** sound better? 

I didn't emitted any opinion before because I didn't actually liked any of the options. Yeast is limited to one type of organism. Culture is too generic. Microbe doesn't always sound like a good thing. At some point I thought of "fermentation_culture", but it is a bit long. But "microorganism" sounds nice to me.

**Comment by pricelessbrewing** [comment]
I had considered it, and my thought on culture was that's what we're buying/using. When we buy a "pitch"/vial/packed/satchet we're buying a culture of microorganisms/microbes. Wlp001 is a culture of English ale yeast, when we make a starter we are propagating a culture. We usually refer to them a strains, but that is not generally applicable to a blended product like roeselare which contains an ale yeast, a sherry strain of bacteria, two brett yeast strains, a lacto culture (does not specify how many strains), and a pedio culture (does not specify how many strains). However culture is still applicable to a blended product. 

Microbe/microorganism both imply a single type, which doesn't apply for blends, dregs, or a spontaneous fermentation. Culture does though. Would have to be microbe(s) and microorganism(s) to be generalized, but culture is universal. 

Either way I'm fine with any of those three.

**Comment by rmsrosa** [comment]
I see your point with the singular form. I still like microorganisms, but I understand the pitfalls. And although the word "culture" alone might have many different social, artistic, and etc. meanings, I guess it is not a big deal. So "culture" it is.
