### ISSUE TITLE
Fermentable types  Grain vs malt, and adjunct?

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#30]
As it stands, version 2.01 does not specify what distinguishes “grain” from “adjunct”. Looking at my current ingredient database in beersmith, it appears that anything that was malted is a grain, while usually unmalted grains are listed as adjuncts. However there’s no formal definition, so some sources/software have some unmalted grains as “grain” instead of “adjunct” and sometimes the same ingredient from different companies is listed differently. 

I propose that anything malted be listed as **“malt”,** while anything unmalted be listed as **“adjunct”.** This supports a formal divide that is clear and is easily distinguishable. In Malt by John Mallet, he simply states “Adjuncts are non-malt sources of fermentable sugars”. Can't argue with the man that wrote the book on malts, right?

Sorry for blowing up everyones notifications, that's my last one for now!

**Comment by pricelessbrewing** [comment]
@rmsrosa  If you wanted something simple to attempt, this is pretty straightforward. 

Rename grain.json to fermentable.json, grain types to malt, references of "flakes" to "flaked" for consistency. 

Will need to adjust the test files, Beer.json, the documentation. It's really just renaming stuff, so you don't really need to worry too much about json structure since it's all in place already. 

If I don't see a comment on this, I'll probably do it on my next day off work (sunday the 4th).

**Comment by rmsrosa** [comment]
Yes, that is a good way to start! I will try that, thanks.

**Comment by pricelessbrewing** [comment]
Question for @beerjson/beerjson-wg regarding the groups vs types for FermentableBase, they seem to both be used to categorize the fermentable. Is group supposed to be a sub category of type? If so, should there be A) A sub group for each type (ie merge extract and dry extract and create groups of dry/liquid), and merge adjunct and grain to grain, then create new group of unmalted? or B) Merge group to type to create one list of categories, something like... 

B)          "enum": [
            "base_malt",
            "caramel",
            "flaked",
            "unmalted",
            "dry_extract",
            "liquid extract",
            "sugar",
            "roasted",
            "specialty",
          ]

Note I removed wheat, and correct speciality spelling to specialty. If we're going to include wheat, we also need to include barley, oat, rice, sorghum, etc. Slippery slope that just undermines the other categories, since wheat is either malted or unmalted it would fall under the appropriate category and be specified in the name of the grain.

**Comment by rmsrosa** [comment]
I agree wheat should be removed, and I think it is superfluous to have a group or subgroups or even include such details in the type object. I would simply stick to how it is in BeerXML 1.0 and 2.0.1, namely, just a type with "grain, adjunct, dry extract,  extract, and sugar.

**Comment by pricelessbrewing** [comment]
Went through all the tests and fermentable.json. This is good now, just need to keep it mind when we get to documentation on what defines each category.
