### ISSUE TITLE
Fix historical misprints

### ISSUE THREAD

**Issue by krutilin** [beerjson/beerjson#4]
For example, "measureable" should be "measurable". Also, need a careful check for other misprints.

**Comment by krutilin** [comment]
Maybe a good idea is to change "measureable_units" to just "units".

**Comment by superroma** [comment]
Let's convert from BeerXML 2 whatever we can convert as is, and leave such decisions to the working group.

**Comment by krutilin** [comment]
As the @superroma said
"note, this is just a name for the schema - there will be no "measurable_units" string anywhere in actual recipe JSON files."

closing the issue.
