### ISSUE TITLE
Record structure and inventory

### ISSUE THREAD

**Issue by rmsrosa** [beerjson/beerjson#42]
I must say I don't like the way BeerXML 2.0.1 defines the ingredient records by including the inventory in the record and the amount inside the inventory. Beerjson is currently following this format. (BeerXML 1.0 had "amount" separately, and "inventory" was an extension).

In the hop record, for instance, the inventory is further divided into the fields "leaf", "pellet", and "plug", each of them with their own dictionary (object in JS) with the keys (names) "units" and "mass". My first complaint is that, a given hop variety, even from the same season and vendor, will have different alpha-acid contents depending on whether being a leaf, a pellet, or a plug. So it makes no sense to allow for more than one type in the same record. Besides, there are many other forms of hops, nowadays.

Thus, even with just one type/form of hop it would make more sense to have
```
        "use" : "aroma",
        "type":  "leaf",
        "amount" : {
            "units": "oz",
            "mass": 2.0
          }
        }
```
instead of 
```
        "type" : "aroma",
        "inventory": {
          "leaf": {
            "units": "oz",
            "mass": 2.0
          }
        }
```

If you prefer to keep the key/name "type" for "aroma", etc; we can use {"form" : "leaf}, for instance. That is not the main point, although I prefer "use" for "aroma"/"flavor"/etc. And "type" is usually reserved for something more significant than that, which are not well defined characteristics of a hop addition. So, on a second thought, maybe { "use" : "aroma", "form" : "pellet"} might be best. 

From a practical point of view, it makes it easier to write a software if all "amounts" have the same key "amount", instead of varying according to the type.

My other complain, again from the point of view of developing a software, at least this is the way I see it, is that we would have an "Inventory" object and a "Recipe" object, containing all hops, fermentables, etc., and each record will say the amount in the inventory or in the recipe. Not the other way around.

So, my suggestion is to drop the field "inventory" from all the records, create an "amount" field for the amount, creat a "form" field when appropriate, and change "type" to "use" regarding "aroma", "flavor", etc.. And then "Inventory" could be a Record Set.

I wish I could implement this, if you agree, and submit a PR, but JS is not my thing at all. I hope you don't mind me making suggestions I find relevant.

**Comment by pricelessbrewing** [comment]
+1 for use for aroma/flavor/bitterness and form for pellet/leaf/wet leaf/oil/etc etc. 

Although IMO "use" should go away, it's a missleading misnomer that's a hold over from when we still thought it was that simple. You get bitterness from a 5 minute boil time, just less, and you get aroma and flavor from a 45 minute boil time, just less. I don't think it has a place in the modern brewing process. 

I'm not quite sure I'm following you regarding inventory/variety/recipe changes. 

If you're proposing that each individual object for each hop addition/variety be specific to the "form" then I agree. For the reasons you mentioned, the properties of the hop form are specific to the year, region, crop, and form so having the form be a subset of the main object which has properties of AA, oil content etc is not helpful since it will have different oil content depending on it's form. 


Regarding inventory, does that even matter for the recipe schema? When you're sharing recipes, who cares how much inventory the original brewer has? It doesn't affect the recipe, or the brewing process. That should be something stored on the software, and IMO not something stored in the recipe file.

**Comment by rmsrosa** [comment]
We can drop aroma/flavor/bitterness, I agree it is not of much use.

Yes, I am proposing that each hop addition have a "form", specifying whether it is a pellet/leaf/wet leaf/plug/oil/powder/others, and simply have an "amount" field (as a Mass) and an "amount_as_volume" field (as a Volume, in case of oil), without the "inventory". Similarly, other ingredients should just have "amount" (be it weight or volume, depending on the typical quantity for the ingredient), and, if appropriate, an "amount_as_volume" or "amount_as_weight".

I didn't mean to suggest that we should create an inventory recordset, either inside a recipe or outside. I agree an inventory can be defined in the software but be archived simply as a collection of ingredients.

So, dropping the "use"/"type", we should have something like

``` 
        {
         "name": "Cascade",
        "origin": "US",
        "alpha_acid_units": 5
        "form":  "leaf",
        "amount" : {
            "unit": "g",
            "value": 32.0
          }
        }
```

or

``` 
        {
         "name": "Simcoe CO2 hop extract",
        "origin": "US",
        "supplier": "YCH Hops"
        "alpha_acid_units": 12
        "form":  "extract",
        "amount" : {
            "unit": "g",
            "value": 11.0
          }
        }
```

or

``` 
        {
         "name": "Lemon Drop Hop Oil",
        "origin": "US",
        "supplier": "YCH Hops"
        "alpha_acid_units": 12
        "form":  "oil",
        "amount_as_volume" : {
            "unit": "ml",
            "value": 56
          }
        }
```

I added "supplier" in the snippets above, but I notice the hop schema does not have the "supplier" field. Should we add it? If not, does the validation schema ignores it if it is present or will it fail?

**Comment by pricelessbrewing** [comment]
I agree, but I'd like to get input from @krutilin @superroma @rocketman768 @mikfire. Do you think inventory is a necessary object in the recipe, and hop additions? I don't see much benefit of it.

Regarding supplier, I think it's necessary for yeast and grains, but less so for hops IMO.

**Comment by rmsrosa** [comment]
> Regarding supplier, I think it's necessary for yeast and grains, but less so for hops IMO.

I agree. Although it should be trivial to include supplier as a non-required object, retailers usually do not advertise the supplier of hops as they do with malts and yeasts, so that is not really a significant issue.

**Comment by mikfire** [comment]
I think not including inventory is a good idea. It doesn't really make much sense if we are (say) copying recipes about. What's in my inventory certainly isn't in yours. And I think that should apply to almost any thing.

One small suggestion. Consider having just one "amount" object, and then having a "type" of "mass", "volume" or "unit" (for use with whirfloc tablets or a vial of clarityfirm). If you decide against it, then consider having a "amount_as_mass" and "amount_as_volume". I really prefer explicit declarations over inferences.

**Comment by pricelessbrewing** [comment]
I think simplifying to one amount object would be nice, and feel that amount as mass and amount as volume are redundant given the explicit unit type. A unit type of grams, or mL, or "each" explicitly declares the quantity being measured.

**Comment by rmsrosa** [comment]
I think I got ahead of myself. I had not noticed before the part of the schema for corresponding AdditionType of the each of the ingredients (hops, yeast, misc, fermentables). The AdditionType already contains the amount and volume fields, so my suggestion to add amount and amount_as_weigth/amount_as_volume is redundant. They are already there. 

Then, dropping Inventory becomes less of an issue, now, it doesn't matter to me if it stays or goes away. 

But the suggestions of creating an object with the name "form" for pellet/leaf/wet leaf/oil/etc and allowing only one form in the record remain, and the suggestions of using "unit" in the singular and the generic word "value" instead of explicitly specifying the type of value also remain.

**Comment by superroma** [comment]
> I agree, but I'd like to get input from @krutilin @superroma @rocketman768 @mikfire. Do you think inventory is a necessary object in the recipe, and hop additions? I don't see much benefit of it.

Agreed, Inventory makes no sense as data interchange format, since everybody has different inventory.

**Comment by krutilin** [comment]
Inventory schema and the possibility to validate it is good for software where you store lists of your ingredients, but there is no place for it in data interchange format. Will close this issue.
