### ISSUE TITLE
Adjunct grain vs Adjunct misc. ingredient. 

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#43]
We have two definitions for adjunct ATM, which is going to lead to confusion. 

Grains should be divided into 1) Malt, and 2) Adjunct. This is a distinct categorization with no grey room. All flaked grains and non malted grains are adjuncts. 

Then Misc ingredients should be called such, not adjuncts.

**Comment by rmsrosa** [comment]
I was planning to mention a related question. 

The first thing is that grains.json should actually be fermentables.json (as in BeerXML 1.0 and 2.01). It makes no sense to have a type object, inside grains.json, that allows for sugar and extract, for instance. This would have an effect in a few other parts. For instance, in recipes.json, 
```
            "grain_bill": {
              "$ref": "grain.json#/definitions/FermentableAdditionType"
            },
```
should be changed to
```
            "fermentable_bill": {
              "$ref": "fermentables.json#/definitions/FermentableAdditionType"
            },
```
and
```
            "adjuncts": {
              "$ref": "misc.json#/definitions/MiscellaneousAdditionType"
            },
```
should be changed to
```
            "miscellaneous_additions": {
              "$ref": "misc.json#/definitions/MiscellaneousAdditionType"
            },
```

In this way, we shouldn't have Grains, hence no need to divide them between malts and adjuncts. And adjunct does not appear explicitly neither in miscellaneous, nor in fermentables (except in the description, but not in the actual objects.

**Comment by pricelessbrewing** [comment]
Completed
