### ISSUE TITLE
Blending as a recipe property with daughter recipe objects. 

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#46]
This should actually be fairly doablefor the schema, since we’re already using arrays, this could be as simple as the main recipe object having an additional optional boolean property of "blended recipe" 

then component A: Percentage XX%, "Name", Component B: Percentage XX, "Name".

Then having two additional recipe objects of A and B. The software will of course have to perform the resulting math.

 Additionally it might be good to support blend component beers as a volume as well as a percentage. So you could do a blend of 5 gallons of recipe A, and 1 gallon of recipe B without the user having to do math. Up to you if you want this to be supported in the recipe, but if not it might resultant in weird math occurying like a recipe having 4.3254634% of Recipe A. 

I don't think I'm qualified to do this myself.

**Comment by rmsrosa** [comment]
Do you mean to have two recipe objects inside another recipe object? I think we could think about that in the future. My software allows that (or will allow, since it is not yet finished), and even more types of blends and partitions, in other parts of the process, and it would indeed be nice to have that included in beerjson, but my concern is that, as I understand it, the meaning of BeerXML and beerjson is to have a minimal complexity so that all softwares should be able to comply. If we make blending possible, some softwares might need some nontrivial changes to comply. I think at this moment we shouldn't plan for that.

**Comment by pricelessbrewing** [comment]
There are many non required properties. This would just be one more, and
would be a huge improvement over the previous beerxml standards, especially
for pros, sour, and funky brewers as I've mentioned previously where
blending is extremely common if not present in the majority of beers.

Imo the schema should support every property necessary to fully describe
the beer, and every step of any possible brewing process.  This may not be
the current goal of the core developers, but I think it's a worthwhile
goal.

**Comment by rmsrosa** [comment]
We may allow non required (non essential) properties that will not prevent a software to properly parse a json recipe, but if blending is not implemented in a software, the software will not read the recipe. I agree we could/should think of that for the future. There are indeed many things that pros (and non-pros) do that do not fit the current softwares, like party-gyle (Fullers), and two or more mashes/boils to fill a fermentor (most of the breweries). But I think it would be nice to have a simpler version of beerjson released sooner, and then we have time to improve it. Anyways, let us hear from the others. If the groups things just the blending is easy, interesting, and not problematic, then no problem.

**Comment by pricelessbrewing** [comment]
Oh nice, parti-gyle could actually be supported in the same way (if we wanted to). Have a single mash object followed by two (or more) daughter recipes with percentages of each runnings (drain off wort from the mash tun).

**Comment by krutilin** [comment]
I think it will be possible to extend the schema for the blending procedures. At least I can't find any fundamental showstoppers for this. 
But better implement this feature when we will have real software with this blending functional. As for now, I will close this issue.
