### ISSUE TITLE
Rename BeerXML.json to Beer.JSON, update tests accordingly

### ISSUE THREAD

**Issue by pricelessbrewing** [beerjson/beerjson#47]
The test files are all still labelled as BeerXML as version 2.01-2.09 if I remember correctly, despite being beerjson files.

**Comment by krutilin** [comment]
Yeah, will fix it. And I suppose we should start using some kind of planning git features. I will check how it works and will prepare planning board.

**Comment by krutilin** [comment]
Done in https://github.com/beerjson/beerjson/pull/49
