### ISSUE TITLE
What do we need for publishing?

### ISSUE THREAD

**Issue by krutilin** [beerjson/beerjson#52]
GitHub pages/site
how to/getting started
documentation
set of tools/conversion/validation

**Comment by superroma** [comment]
Standard itself would be a schema and documentation generated from it.

Optional nice-to-have things:
* Converter from BeerXML 1.
* Sample import/export code with schema verification in JavaScript, PHP, C, Python
* Some sample data

Regarding getting started - getting started with what? Standard development? Or using JSON schema in your app? I guess everybody will have different environments. We can add our code samples after implementation.

**Comment by rmsrosa** [comment]
I will be doing the import/export code with schema verification and the BeerXML 1.0 import/export in Python anyway, for my own project, so I can be responsible for the Python part, although if anyone is quicker than me on that, I won't certainly complain! I have already been looking and testing the jsonschema python module (github.com/Julian/jsonschema), which is included in the anaconda distribution, but I haven't completely worked it out. But I do understand it is not the priority now and it may wait till version 1.0.1 (or 1-0-1).
