### ISSUE TITLE
Missing documentation for FermentableType

### ISSUE THREAD

**Issue by MichaelWashburnJr** [beerjson/beerjson#76]
The link from Fermentable to FermentableType leads to no where. (https://github.com/beerjson/beerjson/blob/master/docs/BeerXML.json.md#fermentable)

**Comment by superroma** [comment]
This is caused by #78 - currently a root doc file is empty. Will be fixed after root schema review

**Comment by superroma** [comment]
This was a link missing. Actual documentation is here: https://github.com/beerjson/beerjson/blob/master/docs/fermentable.json.md

**Comment by pricelessbrewing** [comment]
Closing issue.
