### ISSUE TITLE
General Documentation Issues

### ISSUE THREAD

**Issue by MichaelWashburnJr** [beerjson/beerjson#77]
In general, the documentation provided so far here is really difficult to read and leaves me feeling more confused than I am just reading through the source code. I feel like [this page](https://github.com/beerjson/beerjson/blob/master/docs/BeerXML.json.md) needs to actually specify the attributes found in a fermentable, hop, etc.. 

Some oddities I've noticed that are tripping me up:
- [fermentables](https://github.com/beerjson/beerjson/blob/master/docs/BeerXML.json.md#fermentables) says its an object, but appears to be a list [in this example](https://github.com/beerjson/beerjson/blob/master/tests/generic/fermentable.json)
- I would expect a [Fermentable](https://github.com/beerjson/beerjson/blob/master/docs/BeerXML.json.md#fermentable) to have a list of attributes, but none are listed, and the link to [FermentableType](https://github.com/beerjson/beerjson/blob/master/docs/fermentables.json.md/#fermentabletype) 404s.
- Recipe Types as defined [here](https://github.com/beerjson/beerjson/blob/master/docs/recipes.json.md/#recipetype) seem to have the attributes that a recipe has. I'm not sure what the difference between RecipeType and Recipe is, comparing examples to documentation

I'd love to start diving in to get an official release of this out, but I'm finding it hard to grasp the concepts. It seems like there's a need for one page which specifies the schema in its entirety, including fermentables, fermentable types, hops, hop types, recipes, procedures, equipment, etc.

**Comment by pricelessbrewing** [comment]
Related to issue #13.

Is this corrected in the documentation refactor pull request by krutlin?

**Comment by superroma** [comment]
Hi, I'm still working on the generator, so most actual docs are in this branch: https://github.com/beerjson/beerjson/tree/gen-docs-rewrite 
It is not complete, but I'll look at reported issues in coming days.

**Comment by MichaelWashburnJr** [comment]
@pricelessbrewing It's certainly related, but definitely not corrected. Although now I know the right place to get involved. I'll leave any additional feedback on PR #13

**Comment by MichaelWashburnJr** [comment]
As a follow up, @superroma Have you found writing code to generate docs based on the `.json` files to be more tedious than just writing the documentation by hand? In my experience, having a human in the loop with regards to documentation generally makes it more readable and useful. Although more care has to be taken to make sure it's updated when the specification changes

**Comment by superroma** [comment]
At this point schema is changing a lot, so generating docs is much easier than updating by hand. We not generating descriptions, just an overall structure. 

In the future it might require a hand written long pieces of markdown, but I think we can handle this case in generator by having some kind of include directive.

**Comment by superroma** [comment]
I have merged latest docs into master. There is still issue #79 is open, but all other shemas should have a documentation generated.

**Comment by pricelessbrewing** [comment]
@superroma How does this work? I can't seem to get gen-docs.js to run.

**Comment by pricelessbrewing** [comment]
@superroma Having issues with this, how do we run gen-docs.js ? I keep getting error below, I need to generate document for #51 before submitting PR. 


```
Error: ENOENT: no such file or directory, open 'D:\Software\Github\beerjson\js\docs\beer.json.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at fs.readdirSync.forEach.j (D:\Software\Github\beerjson\js\gen-docs.js:9:8)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\Software\Github\beerjson\js\gen-docs.js:8:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by pricelessbrewing** [comment]
@beerjson/beerjson-wg While I don't know how much I can help with the generator, I plan on going through and adding descriptions to anything that needs a description to help fill in the documentation a bit more.

**Comment by superroma** [comment]
I think I've fixed all issues with documentation.

Currently we don't process nested object property type definition like this one:
https://github.com/beerjson/beerjson/blob/87325891351d62f0db2a6e5699589d2c329a0735/json/culture.json#L75-L91

I suggest extract such definitions into its own type and leave a reference there. 

So, i guess we are ready to add missing definitions.
