### ISSUE TITLE
hop.json VarietyInformation properties missing

### ISSUE THREAD

**Issue by neyc** [beerjson/beerjson#82]
For exchanging recipes it would not be necessary. But to exchange hop variety information you may consider following additional properties:
total_oils: "type": "number"
geraniol: "type": "number"
b-pinene: "type": "number"
linalool:: "type": "number"
origin: "type": "string"
polyphenols:"type": "number"
xanthohumol::"type": "number"

See https://ychhops.com/varieties/bitter-gold  which shows data of geraniol, b-pinene and linalool
Hopsteiner provides sometimes xanthohumol content. See https://www.hopsteiner.com/variety-data-sheets/Bitter-Gold/
polyphenols data are shown by Barth-Haas see https://www.barthhaasgroup.com/images/downloads/varieties/sortenblattenglgermanyhallertauermittelfrueh.pdf

additional aroma information as Pine, Grapefruit, floral might be nice too.

**Comment by pricelessbrewing** [comment]
Of note the industry standard for total oils is mL per 100g, while the specific oil content (ie linalool:) is expressed as a percentage of the total oil content. 

Aroma/flavor info would best be placed in a description text imo.

**Comment by pricelessbrewing** [comment]
Additionally, I think the IBU method in hop.json belongs in recipe.json or beer.json as hop.json simply refers to the hop properties and addition type, not the formula used to determine the IBUs, nor does it store the IBUs themselves. 

Similarly SRM formula should be in recipe or beer.json?

**Comment by pricelessbrewing** [comment]
Things like thiols, xanthohumol, and polyphenols are not widely used in most hop analysis and the measurements aren't entirely standardized. I'm keeping them as a percentage atm, but be aware that this may change in the future. I've contacted a couple places like yakima valley, hopsteiner etc. Will open a new issue when information changes.
