### ISSUE TITLE
culture.json yeast types

### ISSUE THREAD

**Issue by ingoogni** [beerjson/beerjson#86]
kviek should be kveik

don't use 'lager', use bottom-fermenting
don't use 'ale', use top-fermenting

as lager and ale don't describe cultures but beer style in the broader sense or processes.

**Comment by pricelessbrewing** [comment]
Thanks for the typo correction! 

For ale/lager, yeast labs report their cultures using that classification, and is the industry standard. 

Personally I'd prefer the scientific names, but those aren't all known for each strain, and is constantly being corrected as genetic sequencing becomes more commonplace.

**Comment by ingoogni** [comment]
Why not both, where the type_descriptive can be somewhat ambivalent like in ale/lager that is specific for the English language area but is not seen as such in other parts of the world where lager is a process, regardless of species type. It also allows for generic and special "doubles" like wine and champagne.
I wouldn't worry too much with name changes in the scientific field as they often can be tracked and dated quite good.

"properties": {
        "name": {
          "type": "string"
        },
        "type_desc(riptive)": {
          "type": "string",
          "enum": [
            "ale",
"bacteria",.....]},
        "type_science":{
          "type": "string",
          "enum": [
            "S. cerevisiae var. diastatic",
            "S. cerevisiae x kudriavzevii",
            "S. paradoxus", ......]},

**Comment by pricelessbrewing** [comment]
Thanks @Slik13 for the quick PR! 

I'm open to the idea of having a property of top/bottom fermenting, but not keen on the idea of it replacing ale/lager. I'll have to check on how yeast labs, breweries, and/or homebrew shops in non-north american regions classify their cultures. Ale/lager/brett/ etc are the clear industry standard in NA, and I believe at least he UK and belgium (setting aside that they prefer belgian yeast by a classification type and not an origin type)  as well. 

I'd love to get the scientific names as well, but I'm not aware of any labs that report that information "officially" through the manufacturer product document, on the package, or on the website page for that strain. Apart from the general ale/lager = S. cerevisiae / S. pastorianus, most lacto cultures are identified, and they're getting better about reporting diastatic in the last year. But largely it would have to rely on second hand reports.

**Comment by ingoogni** [comment]
A while ago I contacted Whitelabs about that and their answer was that they will publish scientific names in the future. Whitelabs and Wyeast already gave information on var. diastaticus and the rest will follow.
Many of the wine yeast and bacteria are identified by their "producers".
I think beerjson should be prepared for that.

**Comment by slik13** [comment]
I think the question becomes is that useful information that can be acted upon. If manufacturers do decide to publish this information, I fail to see the obvious benefit of allowing cultures to specify their scientific name other than to add extra information to the object that may or may not be accurate.

Unless you had a specific use case in mind.

**Comment by ingoogni** [comment]
"Unless you had a specific use case in mind."

As there is an inventory item: yeast banking. 

Also not every yeast or culture comes from one of the big labs, people harvest yeasts from nature, exchange yeasts etc.

**Comment by slik13** [comment]
You have a point, plus I see no harm in adding it.

I agree with @pricelessbrewing that using scientific name might not be the best descriptor and something more generic might allow more flexibility.

**Comment by pricelessbrewing** [comment]
>Also not every yeast or culture comes from one of the big labs, people harvest yeasts from nature, exchange yeasts etc.

This is supported in the type enum list via spontaneous, other, mixed-culture. 

>Nature / exchange yeasts

Good point. Recommend changing "laboratory" property to "origin". Add description to include examples of lab, brewery/brewer, wild, etc.

**Comment by pricelessbrewing** [comment]
Going to close this for now, since the root issue was patched. We can revisit taxonomy classification later
