### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by tgangso** [beerjson/beerjson#92]
Typescript would be a perfect fit for this file format. Would be nice to have typings.

**Comment by krutilin** [comment]
Yes, type definitions are good.

It is possible to convert schema to the TypeScript or Flow types. There are some solutions for automated conversion:
https://www.npmjs.com/package/json-schema-to-typescript
https://www.npmjs.com/package/json-schema-to-flow-type

we could apply them or do a manual conversion after cleaning up beerjson and releasing schema.

**Comment by tgangso** [comment]
Great!

**Comment by krutilin** [comment]
@tgangso btw flow definitions added. See latest commits.

**Comment by superroma** [comment]
I added TypeScript typings generation (regenerated with documentation on `npm run gen-docs`)

Current result is here: https://github.com/beerjson/beerjson/blob/master/types/ts/beerjson.d.ts 

Note, that I did not use the result in real TS code, but TS plugin in VS gives me no syntax errors, so please test it and let us know if there are any issues with generated types.
